"""Sample ASTs for unit testing Analysis

here we mock the outputs of pycparser.parse_file

the unit test is not about testing the functionality of the parser,
instead what happens on different files it returns, so here are some
examples of possible outputs.
"""

from pycparser.c_ast import FileAST, FuncDef, Decl, FuncDecl, TypeDecl, \
    IdentifierType, Compound, Constant, While, BinaryOp, ID, Assignment, If

# AST generated by pycparser for empty_main.c
#
# int main(){
# }
#

EMPTY_MAIN = FileAST(ext=[FuncDef(decl=Decl(
    name='main', quals=[], storage=[],
    funcspec=[],
    type=FuncDecl(
        args=None,
        type=TypeDecl(
            declname='main',
            quals=[],
            type=IdentifierType(
                names=['int']))),
    init=None, bitsize=None),
    param_decls=None,
    body=Compound(block_items=None))])

# AST generated by pycparser for infinite_2.c, this program:
#
# int main(){
#     int X0=1, X1=1;
#     while(X1<10){
#         X0 = X1*X0;
#         X1 = X1+X0;
#     }
# }
#

INFINITE_2C = FileAST(ext=[FuncDef(
    decl=Decl(name='main', quals=[],
              storage=[],
              funcspec=[],
              type=FuncDecl(
                  args=None, type=TypeDecl(
                      declname='main', quals=[],
                      type=IdentifierType(
                          names=['int']))),
              init=None, bitsize=None),
    param_decls=None, body=Compound(
        block_items=[Decl(name='X0',
                          quals=[],
                          storage=[],
                          funcspec=[],
                          type=TypeDecl(
                              declname='X0', quals=[],
                              type=IdentifierType(names=['int'])),
                          init=Constant(type='int', value='1'),
                          bitsize=None),
                     Decl(name='X1',
                          quals=[],
                          storage=[],
                          funcspec=[],
                          type=TypeDecl(declname='X1', quals=[],
                                        type=IdentifierType(names=['int'])),
                          init=Constant(type='int', value='1'),
                          bitsize=None
                          ),
                     While(cond=BinaryOp(
                         op='<',
                         left=ID(name='X1'),
                         right=Constant(type='int', value='10')),
                         stmt=Compound(block_items=[
                             Assignment(op='=',
                                        lvalue=ID(name='X0'),
                                        rvalue=
                                        BinaryOp(op='*',
                                                 left=ID(name='X1'),
                                                 right=ID(name='X0'))),
                             Assignment(
                                 op='=',
                                 lvalue=ID(
                                     name='X1'),
                                 rvalue=BinaryOp(
                                     op='+',
                                     left=ID(
                                         name='X1'),
                                     right=ID(
                                         name='X0')))]))]))])

# if statement without braces
#
# int main() {
#      int x;
#      int y;
#      x = 1;
#
#      int x1;
#      int x2;
#      int x3;
#      x1 = 1;
#      x2 = 2;
#      if (x > 0) x3 = 1;
#      else x3 = x2;
#      y = x3;
#  }

IF_WO_BRACES = FileAST(ext=[FuncDef(decl=Decl(
    name='main',
    quals=[
    ],
    storage=[
    ],
    funcspec=[
    ],
    type=FuncDecl(args=None,
                  type=TypeDecl(
                      declname='main',
                      quals=[
                      ],
                      type=IdentifierType(
                          names=[
                              'int'
                          ]
                      )
                  )
                  ),
    init=None,
    bitsize=None
),
    param_decls=None,
    body=Compound(block_items=[Decl(name='x',
                                    quals=[
                                    ],
                                    storage=[
                                    ],
                                    funcspec=[
                                    ],
                                    type=TypeDecl(
                                        declname='x',
                                        quals=[
                                        ],
                                        type=IdentifierType(
                                            names=[
                                                'int'
                                            ]
                                        )
                                    ),
                                    init=None,
                                    bitsize=None
                                    ),
                               Decl(name='y',
                                    quals=[
                                    ],
                                    storage=[
                                    ],
                                    funcspec=[
                                    ],
                                    type=TypeDecl(
                                        declname='y',
                                        quals=[
                                        ],
                                        type=IdentifierType(
                                            names=[
                                                'int'
                                            ]
                                        )
                                    ),
                                    init=None,
                                    bitsize=None
                                    ),
                               Assignment(
                                   op='=',
                                   lvalue=ID(
                                       name='x'
                                   ),
                                   rvalue=Constant(
                                       type='int',
                                       value='1'
                                   )
                               ),
                               Decl(name='x1',
                                    quals=[
                                    ],
                                    storage=[
                                    ],
                                    funcspec=[
                                    ],
                                    type=TypeDecl(
                                        declname='x1',
                                        quals=[
                                        ],
                                        type=IdentifierType(
                                            names=[
                                                'int'
                                            ]
                                        )
                                    ),
                                    init=None,
                                    bitsize=None
                                    ),
                               Decl(name='x2',
                                    quals=[
                                    ],
                                    storage=[
                                    ],
                                    funcspec=[
                                    ],
                                    type=TypeDecl(
                                        declname='x2',
                                        quals=[
                                        ],
                                        type=IdentifierType(
                                            names=[
                                                'int'
                                            ]
                                        )
                                    ),
                                    init=None,
                                    bitsize=None
                                    ),
                               Decl(name='x3',
                                    quals=[
                                    ],
                                    storage=[
                                    ],
                                    funcspec=[
                                    ],
                                    type=TypeDecl(
                                        declname='x3',
                                        quals=[
                                        ],
                                        type=IdentifierType(
                                            names=[
                                                'int'
                                            ]
                                        )
                                    ),
                                    init=None,
                                    bitsize=None
                                    ),
                               Assignment(
                                   op='=',
                                   lvalue=ID(
                                       name='x1'
                                   ),
                                   rvalue=Constant(
                                       type='int',
                                       value='1'
                                   )
                               ),
                               Assignment(
                                   op='=',
                                   lvalue=ID(
                                       name='x2'
                                   ),
                                   rvalue=Constant(
                                       type='int',
                                       value='2'
                                   )
                               ),
                               If(
                                   cond=BinaryOp(
                                       op='>',
                                       left=ID(
                                           name='x'
                                       ),
                                       right=Constant(
                                           type='int',
                                           value='0'
                                       )
                                   ),
                                   iftrue=Assignment(
                                       op='=',
                                       lvalue=ID(
                                           name='x3'
                                       ),
                                       rvalue=Constant(
                                           type='int',
                                           value='1'
                                       )
                                   ),
                                   iffalse=Assignment(
                                       op='=',
                                       lvalue=ID(
                                           name='x3'
                                       ),
                                       rvalue=ID(
                                           name='x2'
                                       )
                                   )
                               ),
                               Assignment(
                                   op='=',
                                   lvalue=ID(
                                       name='y'
                                   ),
                                   rvalue=ID(
                                       name='x3'
                                   )
                               )
                               ]
                  )
)
])

# same if statement but with braces
#
# int main() {
#      int x;
#      int y;
#      x = 1;
#
#      int x1;
#      int x2;
#      int x3;
#      x1 = 1;
#      x2 = 2;
#      if (x > 0) {
#         x3 = 1;
#      }
#      else {
#         x3 = x2;
#      }
#      y = x3;
#  }

IF_WITH_BRACES = FileAST(ext=[FuncDef(decl=Decl(
    name='main',
    quals=[
    ],
    storage=[
    ],
    funcspec=[
    ],
    type=FuncDecl(args=None,
                  type=TypeDecl(
                      declname='main',
                      quals=[
                      ],
                      type=IdentifierType(
                          names=[
                              'int'
                          ]
                      )
                  )
                  ),
    init=None,
    bitsize=None
),
    param_decls=None,
    body=Compound(block_items=[Decl(name='x',
                                    quals=[
                                    ],
                                    storage=[
                                    ],
                                    funcspec=[
                                    ],
                                    type=TypeDecl(
                                        declname='x',
                                        quals=[
                                        ],
                                        type=IdentifierType(
                                            names=[
                                                'int'
                                            ]
                                        )
                                    ),
                                    init=None,
                                    bitsize=None
                                    ),
                               Decl(name='y',
                                    quals=[
                                    ],
                                    storage=[
                                    ],
                                    funcspec=[
                                    ],
                                    type=TypeDecl(
                                        declname='y',
                                        quals=[
                                        ],
                                        type=IdentifierType(
                                            names=[
                                                'int'
                                            ]
                                        )
                                    ),
                                    init=None,
                                    bitsize=None
                                    ),
                               Assignment(
                                   op='=',
                                   lvalue=ID(
                                       name='x'
                                   ),
                                   rvalue=Constant(
                                       type='int',
                                       value='1'
                                   )
                               ),
                               Decl(
                                   name='x1',
                                   quals=[
                                   ],
                                   storage=[
                                   ],
                                   funcspec=[
                                   ],
                                   type=TypeDecl(
                                       declname='x1',
                                       quals=[
                                       ],
                                       type=IdentifierType(
                                           names=[
                                               'int'
                                           ]
                                       )
                                   ),
                                   init=None,
                                   bitsize=None
                               ),
                               Decl(
                                   name='x2',
                                   quals=[
                                   ],
                                   storage=[
                                   ],
                                   funcspec=[
                                   ],
                                   type=TypeDecl(
                                       declname='x2',
                                       quals=[
                                       ],
                                       type=IdentifierType(
                                           names=[
                                               'int'
                                           ]
                                       )
                                   ),
                                   init=None,
                                   bitsize=None
                               ),
                               Decl(
                                   name='x3',
                                   quals=[
                                   ],
                                   storage=[
                                   ],
                                   funcspec=[
                                   ],
                                   type=TypeDecl(
                                       declname='x3',
                                       quals=[
                                       ],
                                       type=IdentifierType(
                                           names=[
                                               'int'
                                           ]
                                       )
                                   ),
                                   init=None,
                                   bitsize=None
                               ),
                               Assignment(
                                   op='=',
                                   lvalue=ID(
                                       name='x1'
                                   ),
                                   rvalue=Constant(
                                       type='int',
                                       value='1'
                                   )
                               ),
                               Assignment(
                                   op='=',
                                   lvalue=ID(
                                       name='x2'
                                   ),
                                   rvalue=Constant(
                                       type='int',
                                       value='2'
                                   )
                               ),
                               If(
                                   cond=BinaryOp(
                                       op='>',
                                       left=ID(
                                           name='x'
                                       ),
                                       right=Constant(
                                           type='int',
                                           value='0'
                                       )
                                   ),
                                   iftrue=Compound(
                                       block_items=[
                                           Assignment(
                                               op='=',
                                               lvalue=ID(
                                                   name='x3'
                                               ),
                                               rvalue=Constant(
                                                   type='int',
                                                   value='1'
                                               )
                                           )
                                       ]
                                   ),
                                   iffalse=Compound(
                                       block_items=[
                                           Assignment(
                                               op='=',
                                               lvalue=ID(
                                                   name='x3'
                                               ),
                                               rvalue=ID(
                                                   name='x2'
                                               )
                                           )
                                       ]
                                   )
                               ),
                               Assignment(
                                   op='=',
                                   lvalue=ID(
                                       name='y'
                                   ),
                                   rvalue=ID(
                                       name='x3'
                                   )
                               )
                               ]
                  )
)
])

# AST generated by pycparser for notinfinite_2.c, this program:
#
# int main(){
#     int X0=1, X1=1;
#     X0 = X1*X0;
#     X1 = X1+X0;
# }

NOT_INFINITE_2C = FileAST(ext=[FuncDef(decl=Decl(
    name='main',
    quals=[
    ],
    storage=[
    ],
    funcspec=[
    ],
    type=FuncDecl(args=None,
                  type=TypeDecl(
                      declname='main',
                      quals=[
                      ],
                      type=IdentifierType(
                          names=[
                              'int'
                          ]
                      )
                  )
                  ),
    init=None,
    bitsize=None
),
    param_decls=None,
    body=Compound(
        block_items=[Decl(name='X0',
                          quals=[
                          ],
                          storage=[
                          ],
                          funcspec=[
                          ],
                          type=TypeDecl(
                              declname='X0',
                              quals=[
                              ],
                              type=IdentifierType(
                                  names=[
                                      'int'
                                  ]
                              )
                          ),
                          init=Constant(
                              type='int',
                              value='1'
                          ),
                          bitsize=None
                          ),
                     Decl(name='X1',
                          quals=[
                          ],
                          storage=[
                          ],
                          funcspec=[
                          ],
                          type=TypeDecl(
                              declname='X1',
                              quals=[
                              ],
                              type=IdentifierType(
                                  names=[
                                      'int'
                                  ]
                              )
                          ),
                          init=Constant(
                              type='int',
                              value='1'
                          ),
                          bitsize=None
                          ),
                     Assignment(op='=',
                                lvalue=ID(
                                    name='X0'
                                ),
                                rvalue=BinaryOp(
                                    op='*',
                                    left=ID(
                                        name='X1'
                                    ),
                                    right=ID(
                                        name='X0'
                                    )
                                )
                                ),
                     Assignment(op='=',
                                lvalue=ID(
                                    name='X1'
                                ),
                                rvalue=BinaryOp(
                                    op='+',
                                    left=ID(
                                        name='X1'
                                    ),
                                    right=ID(
                                        name='X0'
                                    )
                                )
                                )
                     ]
    )
)
])
