name: Deploy demo server

on:
  push:
    branches: [ demo-server ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_SA_KEY }}
        promote: false
        version: v1
